### ISSUE TITLE
[BUG]: Performance Issues with TheNewEconomy and LuckPerms on Spigot Server

### ISSUE THREAD

**Issue by EnTIv** [TheNewEconomy/EconomyCore#114]
### TNE Version

0.1.2.8

### Spigot Version

1.19.4

### Your config.yml

https://paste.ubuntu.com/p/v2N2SQFS6P/

### Your latest server log

https://paste.ubuntu.com/p/2pWwyrjFMH/

### What part of TNE is the bug affecting?

Other Plugin Support

### Is your server using online mode?

No

### Issue Description
I am encountering performance issues on my Spigot server when using TheNewEconomy (TNE) with LuckPerms. The server's performance profiling indicates significant time spent on operations related to LuckPerms and TNE interactions. Specifically, methods such as `LuckBalanceContext.calculate()`, `Account.getHoldingsTotal()`, and other related calls are contributing to increased server tick time.

### Server Information
- Spigot version: 1.19.4
- TNE version: 0.1.2.8
- LuckPerms version: v5.4.137

### Profiling Data
![image.png](https://s2.loli.net/2024/08/03/IUezO8ba7nAjCQf.png)

### How to reproduce

1. Start the Spigot server with both TheNewEconomy and LuckPerms installed.
2. Ensuring that `Options.type` is set to `item`.
3. Monitor the server performance using a profiler (as shown in the screenshot provided).

**Comment by creatorfromhell** [comment]
> ### TNE Version
> 0.1.2.8
> 
> ### Spigot Version
> 1.19.4
> 
> ### Your config.yml
> https://paste.ubuntu.com/p/v2N2SQFS6P/
> 
> ### Your latest server log
> https://paste.ubuntu.com/p/2pWwyrjFMH/
> 
> ### What modules are you using?
> _No response_
> 
> ### What part of TNE is the bug affecting?
> Other Plugin Support
> 
> ### Is your server using online mode?
> No
> 
> ### Bug description
> ### Issue Description
> I am encountering performance issues on my Spigot server when using TheNewEconomy (TNE) with LuckPerms. The server's performance profiling indicates significant time spent on operations related to LuckPerms and TNE interactions. Specifically, methods such as `LuckBalanceContext.calculate()`, `Account.getHoldingsTotal()`, and other related calls are contributing to increased server tick time.
> 
> ### Server Information
> * Spigot version: 1.19.4
> * TNE version: 0.1.2.8
> * LuckPerms version: v5.4.137
> 
> ### Profiling Data
> ![image.png](https://camo.githubusercontent.com/0d82c5cea910328c433250a2ed27edf978e120add7c54d05a6332027b370e65a/68747470733a2f2f73322e6c6f6c692e6e65742f323032342f30382f30332f4955657a4f386261376e416a4351662e706e67)
> 
> ### How to reproduce
> 1. Start the Spigot server with both TheNewEconomy and LuckPerms installed.
> 2. Ensuring that `Options.type` is set to `item`.
> 3. Monitor the server performance using a profiler (as shown in the screenshot provided).

LuckPermsHook was disabled in a recent version, please try an updated version. 0.1.2.8 is outdated by about 5 months and 3 releases.
