### ISSUE TITLE
[BUG]: It doesn't work on Folia 1.20.6

### ISSUE THREAD

**Issue by DamAlyuk** [TheNewEconomy/EconomyCore#129]
### TNE Version

Last

### Spigot Version

1.20.6

### Your config.yml

-

### Your latest server log

-

### What part of TNE is the bug affecting?

Won't Startup

### Is your server using online mode?

No

### Bug description

![image](https://github.com/user-attachments/assets/6a54fe20-55d5-4fca-a4b2-1eb48335a1b1)

Says it's even not for Folia

I have the original latest 1.20.6 Folia build

### How to reproduce

Add Folia support

**Comment by creatorfromhell** [comment]
> ### TNE Version
> Last
> 
> ### Spigot Version
> 1.20.6
> 
> ### Your config.yml
> 
> ### Your latest server log
> 
> ### What modules are you using?
> _No response_
> 
> ### What part of TNE is the bug affecting?
> Won't Startup
> 
> ### Is your server using online mode?
> No
> 
> ### Bug description
> ![image](https://private-user-images.githubusercontent.com/170083491/364439153-6a54fe20-55d5-4fca-a4b2-1eb48335a1b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjQzNjUsIm5iZiI6MTcyNTQ2NDA2NSwicGF0aCI6Ii8xNzAwODM0OTEvMzY0NDM5MTUzLTZhNTRmZTIwLTU1ZDUtNGZjYS1hNGIyLTFlYjQ4MzM1YTFiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxNTM0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjBkYzg3YTJlNDQ2MDA4Y2NhY2QwYjkyNjRkMTljMGZmZWI5ZTdkODY5MTlhYWM0N2JiNDY2ZjE0YWI1OTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OJx6VkIvRtehkIQ8WZ4wT_ARfT15cvfd9UxR1AI-7sM)
> 
> Says it's even not for Folia
> 
> I have the original latest 1.20.6 Folia build
> 
> ### How to reproduce
> Add Folia support

This was fixed in the latest beta build on the discord.
