### ISSUE TITLE
[FEAT]: Use Adventure's Placeholder.unparsed

### ISSUE THREAD

**Issue by creatorfromhell** [TheNewEconomy/EconomyCore#20]
### Feature Description

Self explanatory.

### Reasoning

Gud!

**Comment by BrycensRanch** [comment]
… I was tired of my lady
We'd been together too long
Like a worn out recording
Of a favorite song
So while she lay there sleeping
I read the paper in bed
And in the personal columns
There was this letter I read
… "If you like piña coladas
And getting caught in the rain
If you're not into yoga
If you have half a brain
If you like making love at midnight
In the dunes on the cape
Then I'm the love that you've looked for
Write to me, and escape"
… I didn't think about my lady
I know that sounds kind of mean
But me and my old lady
Had fallen into the same old dull routine
So I wrote to the paper
Took out a personal ad
And though I'm nobody's poet
I thought it wasn't half bad
… "Yes, I like piña coladas
And getting caught in the rain
I'm not much into health food
I am into champagne
I've got to meet you by tomorrow noon
And cut through all this red tape
At a bar called O'Malley's
Where we'll plan our escape"
… So I waited with high hopes
And she walked in the place
I knew her smile in an instant
I knew the curve of her face
It was my own lovely lady
And she said, "Aw, it's you"
Then we laughed for a moment
And I said, "I never knew"
… "That you liked piña coladas
And getting caught in the rain
And the feel of the ocean
And the taste of champagne
If you like making love at midnight
In the dunes on the cape
You're the lady I've looked for
Come with me, and escape"
… "If you like piña coladas
And getting caught in the rain
If you're not into yoga
If you have half a brain
If you like making love at midnight
In the dunes on the cape
Then I'm the love that you've looked for
Write to me, and escape"
… "Yes, I like piña coladas
And getting caught in the rain
I'm not much into health food
I am into champagne
I've got to meet you by tomorrow noon
And cut through all this red tape
At a bar called O'Malley's
Where we'll plan our escape"

**Comment by creatorfromhell** [comment]
Not really needed at this time.
