### ISSUE TITLE
[BUG]: All messages just appear as `Messages.foo.bar`

### ISSUE THREAD

**Issue by r0xANDt0l** [TheNewEconomy/EconomyCore#46]
### TNE Version

0.1.20.0-PRE-8

### Spigot Version

1.19.4

### Your config.yml

https://paste.ee/p/Pa0WH

### Your latest server log

https://mclo.gs/jQreD1N

### What part of TNE is the bug affecting?

Other Plugin Support

### Is your server using online mode?

No

### Bug description

When you try to run a command that gives an output, it just spits what I put in the title, but chaning `foo.bar`

on `/theneweconomy:ecoadmin`:
![imagen](https://github.com/TheNewEconomy/EconomyCore/assets/41841903/4ff369d7-90c2-4b93-802c-a242a3bb8043)

on `/tne`:
![imagen](https://github.com/TheNewEconomy/EconomyCore/assets/41841903/9d56293f-760d-4194-bd2c-a8ba964f6e36)

### How to reproduce

1. Switch from pre-rewrite
2. try to use TNE commands
3. see errors

**Comment by creatorfromhell** [comment]
As stated in the information for the beta testing, you'll have to let all configurations regenerate. These linked ones are still the old files.

**Comment by r0xANDt0l** [comment]
Ah

**Comment by r0xANDt0l** [comment]
Yep, that fixed it.
