### ISSUE TITLE
[BUG]: $ Offset between multiple servers on the same DB

### ISSUE THREAD

**Issue by dotI0** [TheNewEconomy/EconomyCore#57]
### TNE Version

0.1.2.0

### Spigot Version

1.20.1

### Your config.yml

https://pastebin.com/BMnK6Zkm

### Your latest server log

https://pastebin.com/W59bFTjv

### What part of TNE is the bug affecting?

Won't Startup

### Is your server using online mode?

Yes

### Bug description

I deleted the TNE folder and let it recreate with v0.1.2.0.
Then I reconfigured the MySQL connection. 

Unfortunately, the plugin won't load with MySQL enabled.
See Here: https://pastebin.com/RgpktkVG

But the plugin created some tables on the configured database.
These tables are different from the tables versions before.
My next question is, how to convert the data to the new database format?
Or is it possible to use the old table format?

![image](https://github.com/TheNewEconomy/EconomyCore/assets/54602589/e642b407-7eab-4c18-a1e4-9ebb92282597)
These are the tables newly created. (Tested with other prefix)
![image](https://github.com/TheNewEconomy/EconomyCore/assets/54602589/ed9380ce-c82d-42e7-bc1c-4f8284841898)
These are the original tables I want to use or convert.

Here is my data.yml: (user, password, db censored)
https://pastebin.com/btbxpLbr

Why does the plugin won't load with MySQL and how to convert my database?

The version I used before was TNE-0.1.1.17-PRE-2.

### How to reproduce

Try to use 0.1.2.0 with MySQL and an old database from versions before.

**Comment by creatorfromhell** [comment]
This specific thing was outlined on the front page of spigot. https://github.com/TheNewEconomy/EconomyCore/wiki/Converting-From-Pre-0.1.2.0-Builds

**Comment by dotI0** [comment]
That's not resolving the issue with the plugin not loading on SQL mode.
/tne extraxt also seems to extract the wrong values.
The Balances in the Extracted file are different to the values in the database.

**Comment by creatorfromhell** [comment]
> That's not resolving the issue with the plugin not loading on SQL mode. /tne extraxt also seems to extract the wrong values. The Balances in the Extracted file are different to the values in the database.

Read above your MySQL does not fit the requirements specific on the readme. Also make sure you do /TNE save before hand. The values are read from the cache map.

**Comment by dotI0** [comment]
I've missed that in your comment and edited mine later, sorry..
After removing the db file in the TNE directory, it extracted the right values.
(Also different ServerNames in the config.yml are changing the extracting values)

I have to open a ticket to my server-host regarding the SQL version.
There is no possibility to run tne with an older version?

**Comment by dotI0** [comment]
My Database-Host told me, that the database is running mysql Ver 14.14 Distrib 5.7.42, for Linux (x86_64).
14.14 is newer then 8.0+ or am I wrong?

**Comment by creatorfromhell** [comment]
> My Database-Host told me, that the database is running mysql Ver 14.14 Distrib 5.7.42, for Linux (x86_64). 14.14 is newer then 8.0+ or am I wrong?

Ah so going off the technical terms, then you'll need to ask them what distrib, it'll need to be 8.0

**Comment by dotI0** [comment]
Okay I've created an 8.1.0 database and got TNE to run.

![image](https://github.com/TheNewEconomy/EconomyCore/assets/54602589/47f6b59d-1593-4107-981d-b0f1896ffedd)
But after importing the extracted file the format seems to be messed up?
What is wrong?

**Comment by creatorfromhell** [comment]
Seems like an issue with the character encoding on your server, is this what it looks like in extracted.yml?

**Comment by dotI0** [comment]
Never mind, My SQL Viewer has an option to view Binary Data as Text..
The Viewer thought the uuid is binary because of the missing - in the new format.

Thanks for your Help!

**Comment by dotI0** [comment]
The Currecy-ID was different. Now I have my balance on both servers.

But when I give me 10$ on server 1 and change to server 2, there are 10$ missing..
Servers are 10$ off but the database has the correct value.

**Comment by dotI0** [comment]
Okay, I've looked a bit into it.

Server1: 100$
Server2: 100$
Database: 100$

Give 10 on S1 and Connect to S2 >>

Server1: 110$
Server2: 100$
Database: 110$

Go back to S1 >>

Server1: 110$
Server2: 100$
Database: 100$

That Database Value rotates on every disconnect.

It seems as the database loading of the target server is before the saving of the server I'm coming from.

**Comment by dotI0** [comment]
Okay, thanks! If I can provide information to help, please let me know.

**Comment by dotI0** [comment]
No, I'm testing alone on the server network. But in my opinion, money synchronization should also work with only one player?

**Comment by creatorfromhell** [comment]
> No, I'm testing alone on the server network. But in my opinion, money synchronization should also work with only one player?

Bukkit/spigot don't send the message through bungee unless there is a player online in the server.

**Comment by creatorfromhell** [comment]
@dotI0 Made a queue system that updates the server balances when the player joins after none being online. Tested this using a YAML saving server
https://cdn.discordapp.com/attachments/995859452232220793/1138801529529303080/Untitled_Project.gif

[TNE-Bukkit-0.1.2.0-Pre-23.zip](https://github.com/TheNewEconomy/EconomyCore/files/12302254/TNE-Bukkit-0.1.2.0-Pre-23.zip)

Here is the build to test with, it has both a new bungee jar and bukkit jar. Also, make sure that the ServerID configuration option in both config.ymls for your servers have different UUID.

**Comment by dotI0** [comment]
I tested the build, and it works like a charm!
Thank You!
