### ISSUE TITLE
[BUG]: Conversion troubles

### ISSUE THREAD

**Issue by lubaskinc0de** [TheNewEconomy/EconomyCore#69]
### TNE Version

0.1.2.3

### Spigot Version

1.20.1

### Your config.yml

https://pastebin.com/qgnSkAyJ

### Your latest server log

https://pastebin.com/AFPC2ui1

### What modules are you using?

Conversion

### What part of TNE is the bug affecting?

Other Plugin Support

### Is your server using online mode?

No

### Bug description

Convert from essentials troubles

### How to reproduce

i remove accounts folder, i remove extraction.yml, i put the conversion module to "modules" folder, i remove essentials jar from plugins folder

in my essentials files, i have a 2000 balance, i put the screenshot here 
![image](https://github.com/TheNewEconomy/EconomyCore/assets/100635212/746d44c9-c408-4833-904d-e22f6d5bd9c1)

next, i do /tne convert essentials.

in TNE files i now see my 2000 balance, put the screenshot 
![image](https://github.com/TheNewEconomy/EconomyCore/assets/100635212/de12017c-cea9-47df-9162-eb4685503b51)

i restart the server. do the /papi parse structnull %tne_balance% and i see 200

in my TNE files i now see 
![image](https://github.com/TheNewEconomy/EconomyCore/assets/100635212/0c9f963d-814b-4290-9a6e-7cc7c41aec04)

what im doing wrong?

**Comment by creatorfromhell** [comment]
Where are the currency configurations? The currency main yml file? @lubaskinc0de

**Comment by lubaskinc0de** [comment]
i'm not use bungee, i use clear paper with offline mode

**Comment by creatorfromhell** [comment]
> i'm not use bungee, i use clear paper with offline mode

Ok, I'll be testing with online mode, but this may be a part of the issue. That's why the spigot page showcases no support for offline mode servers.

**Comment by lubaskinc0de** [comment]
https://pastebin.com/XbyW8BxP currency

**Comment by creatorfromhell** [comment]
> https://pastebin.com/XbyW8BxP currency

Check discord, I sent you a message with a fixed jar for offline servers.

**Comment by lubaskinc0de** [comment]
not working

**Comment by lubaskinc0de** [comment]
1. clean server in offline-mode with only essentials (EssentialsX-2.21.0-dev+17-79449ef) and luckperms installed
2. /eco give structnull 10000000000
3. /balance output 10000000000
4. remove the essentials jar, installing latest version of TNE (TNE-BukkitCore-0.1.2.4-Pre1)
5. setting   

#Cracked Server? Set this to true. May cause data issues as spigot/paper UUIDs are unpredictable.
  #Do not change this unless you know what you're doing.
  Offline: true

6. add Conversion (Conversion-0.1.2.0-PRE-1) module
7. restart
8. /balance -> 200
9. /tne convert essentials
10. balance -> 10000000000
11. add essentials jar to plugins
12. restart
13. see useful logs (picture) 
![image](https://github.com/TheNewEconomy/EconomyCore/assets/100635212/c42b3bca-210d-448e-8015-a1db536dbf5c)

14. /balance -> 200

**Comment by lubaskinc0de** [comment]
resolved
