### ISSUE TITLE
[FEAT]: Placeholders for virtual and inventory balance in mixed mode?

### ISSUE THREAD

**Issue by dentatar** [TheNewEconomy/EconomyCore#71]
### Feature Description

It would be nice to be able to get player pocket/virtual/ender balance separately. Internal placeholder to use in messages.yml would be enough i guess. It is already in storage structure and maybe wouldn't be that hard to implement? Thank you!

### Reasoning

Total balance in mixed mode may be confusing sometimes, especially if ender chest is included…

**Comment by creatorfromhell** [comment]
> ### Feature Description
> It would be nice to be able to get player pocket/virtual/ender balance separately. Internal placeholder to use in messages.yml would be enough i guess. It is already in storage structure and maybe wouldn't be that hard to implement? Thank you!
> 
> ### Reasoning
> Total balance in mixed mode may be confusing sometimes, especially if ender chest is included…

So you're looking for this as a placeholder in messages.yml only?

**Comment by dentatar** [comment]
Ye i think this would be enough, just to inform player about his physical/virtual/ender holdings more clearly. I guess also implementing PAPI placeholders would require more work and wouldn't be that useful (but maybe in the future?).

**Comment by creatorfromhell** [comment]
> Ye i think this would be enough, just to inform player about his physical/virtual/ender holdings more clearly. I guess also implementing PAPI placeholders would require more work and wouldn't be that useful (but maybe in the future?).

This has been implemented, will be apart of the next release.

![image](https://github.com/TheNewEconomy/EconomyCore/assets/1010549/7c22dc87-26dc-4f71-861e-4747a6d72ff0)
