### ISSUE TITLE
[BUG]: Old data restoration failed when different uuid user has same name

### ISSUE THREAD

**Issue by ibmibmibm** [TheNewEconomy/EconomyCore#76]
### TNE Version

0.1.2.5

### Spigot Version

1.20.2

### Your config.yml

https://pastebin.ubuntu.com/p/FHpwnby6Z7/

### Your latest server log

https://pastebin.ubuntu.com/p/ZFDKcZ6njc/

### What part of TNE is the bug affecting?

Transactions

### Is your server using online mode?

Yes

### Bug description

Old data restoration failed when different uuid user has same name

### How to reproduce

1. Install with Mariadb
2. Run /tne old

**Comment by creatorfromhell** [comment]
There would be no instance when a UUID user would have the same name unless it's a really old user account, in which it should be removed from extracted.yml before restoring

**Comment by creatorfromhell** [comment]
Do you have a pastebin of your extracted.yml?

**Comment by ibmibmibm** [comment]
Original extracted.yml:
https://pastebin.ubuntu.com/p/zW3g8VS7Gb/
Manually added missing account data:
https://pastebin.ubuntu.com/p/JZV36FNzgy/

**Comment by creatorfromhell** [comment]
> Original extracted.yml: https://pastebin.ubuntu.com/p/zW3g8VS7Gb/ Manually added missing account data: https://pastebin.ubuntu.com/p/JZV36FNzgy/

That didn't clear up to much, what was added to the updated file?

**Comment by ibmibmibm** [comment]
It's two player accounts have the same username(display_name).

**Comment by creatorfromhell** [comment]
> It's two player accounts have the same username(display_name).

Gotcha, I'll probably add a check to remove the duplicate name from the extracted.yml file completely.

**Comment by creatorfromhell** [comment]
Closing as this issue isn't relevant due to userbase being more shifted on the newer recode versions.
