### ISSUE TITLE
[BUG]: Error on startup

### ISSUE THREAD

**Issue by EpixPlays** [TheNewEconomy/EconomyCore#81]
### TNE Version

0.1.2.8-Pre-1, 0.1.2.7

### Spigot Version

1.20.1

### Your config.yml

https://paste.ubuntu.com/p/qK7ND5rtsN/

### Your latest server log

https://paste.ubuntu.com/p/sj9Yg6M4qg/

### What modules are you using?

_None_

### What part of TNE is the bug affecting?

Factions Support

### Is your server using online mode?

Yes

### Bug description

When the plugin starts up, it shows an error and then disables. This only started happening when I added the Saber factions plugin. I have tried 0.1.2.7 and the latest version and it shows the same error in each.

### How to reproduce

1. Install SaberFactions with default settings
2. Install TNE with default settings

**Comment by creatorfromhell** [comment]
@EpixPlays try this jar
[TNE-BukkitCore-0.1.2.8-Pre-1.zip](https://github.com/TheNewEconomy/EconomyCore/files/14154256/TNE-BukkitCore-0.1.2.8-Pre-1.zip)

**Comment by creatorfromhell** [comment]
Closing as I had time to test this locally now:
![image](https://github.com/TheNewEconomy/EconomyCore/assets/1010549/ecdeca96-00fb-4c05-ac11-0029c251ebf5)
