### ISSUE TITLE
[BUG]: Item currency disappear in the inventory at some specific circumstance

### ISSUE THREAD

**Issue by MrLgos** [TheNewEconomy/EconomyCore#86]
### TNE Version

0.1.2.7

### Spigot Version

1.19.4

### Your config.yml

https://paste.ubuntu.com/p/tJqtnhWVn4/

### Your latest server log

https://paste.ubuntu.com/p/yys9pfD8JF/

### What part of TNE is the bug affecting?

Other Plugin Support

### Is your server using online mode?

Yes

### Bug description

I'm using Quickshop-hikari & TNE & Vault on my server, once my server restart, A player doesn't get the item currency he gets when someone buys something from him before we shuts down the server. The money do really added to the towny account (can be checked by using /res command), but when I open his inventory or enderchest, the item currency are not there. So when he join the server, he didnt get the item currency.
Another same circumstance: when my server staff using /spec command and enter spectator mode, during this time someone bought something from his shop, he didnt get the item currency too. I did a test and saw his towny account add 1$ but after he quit from /spec, the 1$ just deleted instead of adding an item currency to his inventory or enderchest.

Also! I have a question, what if the inventory and the enderchest is full, where will the item currency go to? Can we have a /claim command to take the item currency out from a virtual mailbox or something like that?

My request is to send the item currency to the enderchest in real time, if the enderchest is full, temporarily saved to a virtual account which can be taken out by using /claim command.
Thank you!

### How to reproduce

[one.txt](https://github.com/TheNewEconomy/EconomyCore/files/14735743/one.txt)
[penny.txt](https://github.com/TheNewEconomy/EconomyCore/files/14735744/penny.txt)
[USD.txt](https://github.com/TheNewEconomy/EconomyCore/files/14735745/USD.txt)

The first player enter spectator mode and let another player /pay the first player 1$(item currency) and check if the first player's inventory/enderchest have the item currency. When the first player quit from spectator mode, check again.
The first player go offline and the second player buy something from the first player's shop, check if the first player's inventory/enderchest have the item currency. Restart the server, and let the first player join game to see if the item currency add to his inventory/enderchest.

My request is to send the item currency to the enderchest in real time, if the enderchest is full, temporarily saved to a virtual account which can be taken out by using /claim command.

TNE is a wonderful economy plugin, we can not find a better supported plugin like it. Thank you for your developing

**Comment by creatorfromhell** [comment]
> ### TNE Version
> 0.1.2.7
> 
> ### Spigot Version
> 1.19.4
> 
> ### Your config.yml
> https://paste.ubuntu.com/p/tJqtnhWVn4/
> 
> ### Your latest server log
> https://paste.ubuntu.com/p/yys9pfD8JF/
> 
> ### What modules are you using?
> _No response_
> 
> ### What part of TNE is the bug affecting?
> Other Plugin Support
> 
> ### Is your server using online mode?
> Yes
> 
> ### Bug description
> I'm using Quickshop-hikari & TNE & Vault on my server, once my server restart, A player doesn't get the item currency he gets when someone buys something from him before we shuts down the server. The money do really added to the towny account (can be checked by using /res command), but when I open his inventory or enderchest, the item currency are not there. So when he join the server, he didnt get the item currency. Another same circumstance: when my server staff using /spec command and enter spectator mode, during this time someone bought something from his shop, he didnt get the item currency too. I did a test and saw his towny account add 1$ but after he quit from /spec, the 1$ just deleted instead of adding an item currency to his inventory or enderchest.
> 
> Also! I have a question, what if the inventory and the enderchest is full, where will the item currency go to? Can we have a /claim command to take the item currency out from a virtual mailbox or something like that?
> 
> My request is to send the item currency to the enderchest in real time, if the enderchest is full, temporarily saved to a virtual account which can be taken out by using /claim command. Thank you!
> 
> ### How to reproduce
> [one.txt](https://github.com/TheNewEconomy/EconomyCore/files/14735743/one.txt) [penny.txt](https://github.com/TheNewEconomy/EconomyCore/files/14735744/penny.txt) [USD.txt](https://github.com/TheNewEconomy/EconomyCore/files/14735745/USD.txt)
> 
> The first player enter spectator mode and let another player /pay the first player 1$(item currency) and check if the first player's inventory/enderchest have the item currency. When the first player quit from spectator mode, check again. The first player go offline and the second player buy something from the first player's shop, check if the first player's inventory/enderchest have the item currency. Restart the server, and let the first player join game to see if the item currency add to his inventory/enderchest.
> 
> My request is to send the item currency to the enderchest in real time, if the enderchest is full, temporarily saved to a virtual account which can be taken out by using /claim command.
> 
> TNE is a wonderful economy plugin, we can not find a better supported plugin like it. Thank you for your developing

Make sure you run the save before shut down as stated on the spigot page. Also TNE is on version 0.1.2.8, make sure to test on the latest version before posting an issue.
